app-layer:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/app/**/*'

widgets-layer:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/widgets/**/*'

features-layer:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/features/**/*'

entities-layer:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/entities/**/*'

shared-layer:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/shared/**/*'

backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/server/**/*'
      - 'src/app/api/**/*'

database:
  - changed-files:
    - any-glob-to-any-file:
      - 'prisma/**/*'
      - 'src/shared/api/db/**/*'

generated:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/generated/**/*'

configs:
  - changed-files:
    - any-glob-to-any-file:
      - '*.json'
      - '*.config.ts'
      - '.github/**/*'
      - 'pnpm-lock.yaml'
