packages:
  - web

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - nexus-prisma
  - puppeteer
  - zenstack

overrides:
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  tmp@<=0.2.3: '>=0.2.4'
