name: "Close stale pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'Этот PR не обновлялся 30 дней. Он будет закрыт через 7 дней, если не появится новой активности.'
          close-pr-message: 'PR закрыт из-за неактивности.'
          days-before-stale: 30
          days-before-close: 7
